### ISSUE TITLE
Add support for MLX (Apple Silicon)

### ISSUE THREAD

**Issue by abdulfatir** [amazon-science/chronos-forecasting#28]
Should we add support for MLX? This would make inference faster for people with Apple Silicon Macs. Let's discuss.

Some discussion here: https://github.com/ml-explore/mlx-examples/pull/589

cc @sugatoray

**Comment by awni** [comment]
Happy to support you all here. We already have a T5 in MLX so that could serve as a good starting point https://github.com/ml-explore/mlx-examples/tree/main/t5

We would also gladly point people to this e.g. in our community projects page and elsewhere https://github.com/ml-explore/mlx/discussions/654

**Comment by abdulfatir** [comment]
Added in a separate branch (PR #41 and #46): https://github.com/amazon-science/chronos-forecasting/tree/mlx

cc @awni @sugatoray

**Comment by awni** [comment]
That's awesome!!

**Comment by sugatoray** [comment]
@abdulfatir That's great!
